apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipe-jet7960-apivvv
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1002195638358"
    notifications.argocd.argoproj.io/subscribe.on-sync-succeeded: ["sync-complete"]
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/pipe-jet7960-apivvv.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: pipe-jet7960-apivvv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
